package micropolis.client.engine;

public interface Map {
	public int[] getHistoryRes();
	public void setHistoryRes(int[] historyRes);
	public int[] getHistoryCom();
	public void setHistoryCom(int[] historyCom);
	public int[] getHistoryInd();
	public void setHistoryInd(int[] historyInd);
	public int[] getHistoryCrime();
	public void setHistoryCrime(int[] historyCrime);
	public int[] getHistoryPollution();
	public void setHistoryPollution(int[] historyPollution);
	public int[] getHistoryMoney();
	public void setHistoryMoney(int[] historyMoney);
	public String getMap();
	public void setMap(String map);;
	public void setResPop(short resPop);
	public short getResPop();
	public short getComPop();
	public void setComPop(short comPop);
	public short getIndPop();
	public void setIndPop(short indPop);
	public short getResValve();
	public void setResValve(short resValve);
	public short getComValve();
	public void setComValve(short comValve);
	public short getIndValve();
	public void setIndValve(short indValve);
	public int getCityTime();
	public void setCityTime(int cityTime);
	public short getCrimeRamp();
	public void setCrimeRamp(short crimeRamp);
	public short getPolluteRamp();
	public void setPolluteRamp(short polluteRamp);
	public short getLandValueAverage();
	public void setLandValueAverage(short landValueAverage);
	public short getCrimeAverage();
	public void setCrimeAverage(short crimeAverage);
	public short getPollutionAverage();
	public void setPollutionAverage(short pollutionAverage);
	public short getGameLevel();
	public void setGameLevel(short gameLevel);
	public short getEvaluationCityClass();
	public void setEvaluationCityClass(short evaluationCityClass);
	public short getEvaluationCityScore();
	public void setEvaluationCityScore(short evaluationCityScore);
	public int getBudgetTotalFunds();
	public void setBudgetTotalFunds(int budgetTotalFunds);
	public boolean isAutoBulldoze();
	public void setAutoBulldoze(boolean autoBulldoze);
	public boolean isAutoBudget();
	public void setAutoBudget(boolean autoBudget);
	public boolean isAutoGo();
	public void setAutoGo(boolean autoGo);
	public short getCityTax();
	public void setCityTax(short cityTax) ;
	public int getPolicePercent();
	public void setPolicePercent(int policePercent);
	public int getFirePercent();
	public void setFirePercent(int firePercent);
	public int getRoadPercent();
	public void setRoadPercent(int roadPercent);
}
